argo-cd:
#  redis-ha:
#    enabled: true
  dex:
    enabled: false
  crds:
    # -- Install and upgrade CRDs
    install: false
    # -- Keep CRDs on chart uninstall
#    keep: true
    # -- Annotations to be added to all CRDs
  annotations: {}
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
